# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def migrate_images(apps, schema_editor):
    Artist = apps.get_model("hindustani", "Artist")
    Composer = apps.get_model("hindustani", "Composer")
    Release = apps.get_model("hindustani", "Release")
    Instrument = apps.get_model("hindustani", "Instrument")
    Raag = apps.get_model("hindustani", "Raag")
    Taal = apps.get_model("hindustani", "Taal")
    migrate_images_for_class(Artist)
    migrate_images_for_class(Composer)
    migrate_images_for_class(Release)
    migrate_images_for_class(Raag)
    migrate_images_for_class(Taal)
    migrate_images_for_class(Instrument)


def migrate_images_for_class(Klass):
    for item in Klass.objects.all():
        if item.images.count():
            i = item.images.all()[0]
            item.image = i
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('hindustani', '0002_auto_20161005_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordingsection',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='recordingsection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionalias',
            name='section',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laya',
            name='description',
        ),
        migrations.RemoveField(
            model_name='raag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='release',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_artist_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='composer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_composer_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_instrument_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='raag',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_raag_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_release_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='taal',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindustani_taal_image', to='data.Image'),
        ),
        migrations.DeleteModel(
            name='RecordingSection',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionAlias',
        ),
        migrations.RunPython(migrate_images),
    ]
