# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hindustani', '0006_instrumentperformance_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table hindustani_form alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='form',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='laya',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table hindustani_laya alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='laya',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='raag',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table hindustani_raag alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='raag',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taal',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table hindustani_taal alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='taal',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
