# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindustani', '0007_auto_20160912_1519'),
    ]

    operations = [
        migrations.RunSQL('alter table hindustani_artist alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table hindustani_composer alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='composer',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table hindustani_instrument alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='instrument',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table hindustani_recording alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='recording',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table hindustani_release alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='release',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table hindustani_work alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='work',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
