# Generated by Django 2.1.2 on 2019-01-22 14:54

import data.models
from django.db import migrations, models
import django.db.models.deletion
import jingju.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0005_auto_20181205_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('artist_type', models.CharField(choices=[('P', 'Person'), ('G', 'Group')], default='P', max_length=1)),
                ('dummy', models.BooleanField(db_index=True, default=False)),
                ('description_edited', models.BooleanField(default=False)),
                ('romanisation', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('group_members', models.ManyToManyField(blank=True, related_name='groups', to='jingju.Artist')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jingju_artist_image', to='data.Image')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, data.models.ImageMixin),
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jingju_composer_image', to='data.Image')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, data.models.ImageMixin),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percussion', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jingju_instrument_image', to='data.Image')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, data.models.ImageMixin),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('mbid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(jingju.models.JingjuStyle, models.Model),
        ),
        migrations.CreateModel(
            name='RecordingInstrumentalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jingju.Artist')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jingju.Instrument')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jingju.Recording')),
            ],
            bases=(jingju.models.JingjuStyle, models.Model),
        ),
        migrations.CreateModel(
            name='RecordingRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('track', models.IntegerField(blank=True, null=True)),
                ('disc', models.IntegerField(blank=True, null=True)),
                ('disctrack', models.IntegerField(blank=True, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jingju.Recording')),
            ],
            options={
                'ordering': ('track',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('artistcredit', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('artists', models.ManyToManyField(related_name='primary_concerts', to='jingju.Artist')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Collection')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jingju_release_image', to='data.Image')),
                ('recordings', models.ManyToManyField(through='jingju.RecordingRelease', to='jingju.Recording')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(jingju.models.JingjuStyle, models.Model, data.models.ImageMixin),
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('romanisation', models.CharField(max_length=100)),
                ('uuid', models.UUIDField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('citation', models.CharField(blank=True, max_length=100, null=True)),
                ('citation_romanisation', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShengqiangBanshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('romanisation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('composers', models.ManyToManyField(blank=True, related_name='works', to='jingju.Composer')),
                ('lyricists', models.ManyToManyField(blank=True, related_name='lyric_works', to='jingju.Composer')),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.Play')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.Score')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(jingju.models.JingjuStyle, models.Model),
        ),
        migrations.AddField(
            model_name='recordingrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jingju.Release'),
        ),
        migrations.AddField(
            model_name='recording',
            name='instrumentalists',
            field=models.ManyToManyField(related_name='instrumentalist', through='jingju.RecordingInstrumentalist', to='jingju.Artist'),
        ),
        migrations.AddField(
            model_name='recording',
            name='performers',
            field=models.ManyToManyField(to='jingju.Artist'),
        ),
        migrations.AddField(
            model_name='recording',
            name='shengqiangbanshi',
            field=models.ManyToManyField(to='jingju.ShengqiangBanshi'),
        ),
        migrations.AddField(
            model_name='recording',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.Work'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jingju', to='jingju.Instrument'),
        ),
        migrations.AddField(
            model_name='artist',
            name='main_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.Instrument'),
        ),
        migrations.AddField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
