# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
