# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0007_auto_20180830_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordingrelease',
            options={'ordering': ('track',)},
        ),
        migrations.AddField(
            model_name='recordingrelease',
            name='disc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingrelease',
            name='disctrack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingrelease',
            name='track',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
