# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0008_auto_20180830_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='performer',
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
