# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0009_auto_20180904_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordingperformer',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='recordingperformer',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='performers',
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
        migrations.DeleteModel(
            name='RecordingPerformer',
        ),
    ]
