# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0011_auto_20180905_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletype',
            name='transliteration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='role_type',
        ),
        migrations.AddField(
            model_name='artist',
            name='role_type',
            field=models.ManyToManyField(blank=True, null=True, to='jingju.RoleType'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
