# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0012_auto_20180906_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ManyToManyField(blank=True, null=True, to='jingju.RoleType'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='transliteration',
            field=models.CharField(max_length=100),
        ),
    ]
