# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0015_auto_20180907_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='role_type',
        ),
        migrations.AddField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
