# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0016_auto_20180907_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
