# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0018_auto_20180907_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShengqiangBanshi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
        migrations.AddField(
            model_name='recording',
            name='shengqiangbanshi',
            field=models.ManyToManyField(to='jingju.ShengqiangBanshi'),
        ),
    ]
