# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jingju', '0020_auto_20180910_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='role_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jingju.RoleType'),
        ),
    ]
