# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170413_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
