# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180827_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitLog',
        ),
    ]
