# Generated by Django 2.1.2 on 2018-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_visitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='permission',
            field=models.CharField(choices=[('S', 'Staff-only'), ('R', 'Restricted'), ('U', 'Unrestricted')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
