# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:37
from __future__ import unicode_literals
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
            UnaccentExtension()
    ]
