# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondirectory',
            name='collection',
            field=models.UUIDField(db_column='collection_mbid', db_index=True)
        ),
        migrations.AlterField(
            model_name='collectionlogmessage',
            name='collection',
            field=models.UUIDField(db_column='collection_mbid', db_index=True)
        ),
        migrations.AlterField(
            model_name='collectionstate',
            name='collection',
            field=models.UUIDField(db_column='collection_mbid', db_index=True)
        ),
        migrations.AlterField(
            model_name='musicbrainzrelease',
            name='collection',
            field=models.UUIDField(db_column='collection_mbid', db_index=True)
        ),
        migrations.AddField(
            model_name='collection',
            name='collectionid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL("UPDATE dashboard_collection SET collectionid=id"),

        migrations.RemoveField(
            model_name='collection',
            name='id'
        ),
        migrations.AddField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='collectiondirectory',
            name='collection',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.RunSQL("UPDATE dashboard_collectiondirectory dcd SET collection=(select id from dashboard_collection where collectionid=dcd.collection_mbid)"),

        migrations.AddField(
            model_name='collectionlogmessage',
            name='collection',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.RunSQL("UPDATE dashboard_collectionlogmessage dcl SET collection=(select id from dashboard_collection where collectionid=dcl.collection_mbid)"),

        migrations.AddField(
            model_name='collectionstate',
            name='collection',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.RunSQL("UPDATE dashboard_collectionstate dcs SET collection=(select id from dashboard_collection where collectionid=dcs.collection_mbid)"),

        migrations.AddField(
            model_name='musicbrainzrelease',
            name='collection',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.RunSQL("UPDATE dashboard_musicbrainzrelease dmr SET collection=(select id from dashboard_collection where collectionid=dmr.collection_mbid)"),

        ]
