# Generated by Django 2.1.2 on 2019-01-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170403_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfilestate',
            name='state',
            field=models.CharField(choices=[('n', 'Not started'), ('i', 'Importing'), ('f', 'Finished'), ('e', 'Error')], default='n', max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionstate',
            name='state',
            field=models.CharField(choices=[('n', 'Not started'), ('s', 'Scanning'), ('d', 'Scanned'), ('i', 'Importing'), ('f', 'Finished'), ('e', 'Error')], default='n', max_length=10),
        ),
        migrations.AlterField(
            model_name='musicbrainzreleasestate',
            name='state',
            field=models.CharField(choices=[('n', 'Not started'), ('i', 'Importing'), ('f', 'Finished'), ('e', 'Error')], default='n', max_length=10),
        ),
    ]
