# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160919_1822'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE dashboard_collectiondirectory DROP COLUMN collection_mbid"),
        migrations.AlterField(
            model_name='collectiondirectory',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Collection'),
        ),
        migrations.RunSQL("ALTER TABLE dashboard_collectionlogmessage DROP COLUMN collection_mbid"),
        migrations.AlterField(
            model_name='collectionlogmessage',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Collection'),
        ),
        migrations.RunSQL("ALTER TABLE dashboard_collectionstate DROP COLUMN collection_mbid"),
        migrations.AlterField(
            model_name='collectionstate',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Collection'),
        ),
        migrations.RunSQL("ALTER TABLE dashboard_musicbrainzrelease DROP COLUMN collection_mbid"),
        migrations.AlterField(
            model_name='musicbrainzrelease',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collectionid',
            field=models.UUIDField(null=False, unique=True)
        ),
    ]
