# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20151127_1558'),
    ]

    operations = [
        migrations.RunSQL('drop index if exists dashboard_collection_id_like'),
        migrations.RunSQL('drop index if exists dashboard_collectiondirectory_collection_id_like'),
        migrations.RunSQL('drop index if exists dashboard_collectionlogmessage_collection_id_like'),
        migrations.RunSQL('drop index if exists dashboard_collectionstate_collection_id_like'),
        migrations.RunSQL('drop index if exists dashboard_musicbrainzrelease_collection_id_like'),

        migrations.RunSQL('alter table dashboard_collectiondirectory drop constraint collection_id_refs_id_1d937e9a3e736741'),
        migrations.RunSQL('alter table dashboard_collectionlogmessage drop constraint collection_id_refs_id_2430ec1b6df49900'),
        migrations.RunSQL('alter table dashboard_collectionstate drop constraint collection_id_refs_id_5dfe70c4e88ae5f3'),
        migrations.RunSQL('alter table dashboard_musicbrainzrelease drop constraint collection_id_refs_id_5e9871b402af0b5f'),

        migrations.RunSQL('alter table dashboard_collectiondirectory alter COLUMN collection_id type uuid USING ("collection_id"::uuid)'),
        migrations.RunSQL('alter table dashboard_collectionlogmessage alter COLUMN collection_id type uuid USING ("collection_id"::uuid)'),
        migrations.RunSQL('alter table dashboard_collectionstate alter COLUMN collection_id type uuid USING ("collection_id"::uuid)'),
        migrations.RunSQL('alter table dashboard_musicbrainzrelease alter COLUMN collection_id type uuid USING ("collection_id"::uuid)'),
        migrations.RunSQL('alter table dashboard_collection alter COLUMN id type uuid USING ("id"::uuid)'),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.RunSQL('alter table dashboard_collectionfile alter COLUMN recordingid type uuid USING ("recordingid"::uuid)'),
        migrations.AlterField(
            model_name='collectionfile',
            name='recordingid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table dashboard_musicbrainzrelease alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='musicbrainzrelease',
            name='mbid',
            field=models.UUIDField(),
        ),
    ]
