# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 15:30
from __future__ import unicode_literals

import andalusian.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('transliterated_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='AlbumRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Album')),
            ],
            options={
                'ordering': ('track',),
            },
        ),
        migrations.CreateModel(
            name='AlbumType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('transliterated_type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('transliterated_name', models.CharField(blank=True, max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_artist_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_artist_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_artist_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='ArtistAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('primary', models.BooleanField(default=False)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='andalusian.Artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transliterated_name', models.CharField(blank=True, max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('transliterated_name', models.CharField(blank=True, max_length=100)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_genre_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_genre_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_genre_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percussion', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('original_name', models.CharField(blank=True, max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_instrument_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_instrument_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_instrument_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='InstrumentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Instrument')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentSectionPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Instrument')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Mizan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('transliterated_name', models.CharField(blank=True, max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_mizan_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_mizan_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_mizan_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicalSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transliterated_name', models.CharField(blank=True, max_length=100)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_musicalschool_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_musicalschool_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_musicalschool_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Nawba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('transliterated_name', models.CharField(blank=True, max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_nawba_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_nawba_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_nawba_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('transliterated_name', models.CharField(blank=True, max_length=255)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='OrchestraAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orchestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='andalusian.Orchestra')),
            ],
        ),
        migrations.CreateModel(
            name='OrchestraPerformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.BooleanField(default=False)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('instruments', models.ManyToManyField(to='andalusian.Instrument')),
                ('orchestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Orchestra')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('first_words', models.CharField(blank=True, max_length=255, null=True)),
                ('transliterated_first_words', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('transliterated_text', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('transliterated_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_poem_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_poem_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_poem_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('transliterated_title', models.CharField(blank=True, max_length=255)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('archive_url', models.CharField(max_length=255)),
                ('musescore_url', models.CharField(max_length=255)),
                ('artists', models.ManyToManyField(through='andalusian.InstrumentPerformance', to='andalusian.Artist')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Genre')),
                ('images', models.ManyToManyField(related_name='andalusian_recording_image_set', to='data.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='RecordingPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Poem')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Recording')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Recording')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Sanaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transliterated_title', models.CharField(blank=True, max_length=255)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_sanaa_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_sanaa_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_sanaa_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Form')),
                ('images', models.ManyToManyField(related_name='andalusian_section_image_set', to='data.Image')),
                ('mizan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Mizan')),
                ('nawba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Nawba')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Recording')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_section_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_section_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transliterated_name', models.CharField(blank=True, max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_tab_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_tab_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_tab_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('transliterated_title', models.CharField(blank=True, max_length=255)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='andalusian_work_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='andalusian_work_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_work_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(andalusian.models.AndalusianStyle, models.Model),
        ),
        migrations.AddField(
            model_name='section',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Tab'),
        ),
        migrations.AddField(
            model_name='recordingwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Work'),
        ),
        migrations.AddField(
            model_name='recording',
            name='poems',
            field=models.ManyToManyField(through='andalusian.RecordingPoem', to='andalusian.Poem'),
        ),
        migrations.AddField(
            model_name='recording',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='andalusian_recording_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='recording',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_recording_source_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='recording',
            name='works',
            field=models.ManyToManyField(through='andalusian.RecordingWork', to='andalusian.Work'),
        ),
        migrations.AddField(
            model_name='poem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.PoemType'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='groups', through='andalusian.OrchestraPerformer', to='andalusian.Artist'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='images',
            field=models.ManyToManyField(related_name='andalusian_orchestra_image_set', to='data.Image'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='andalusian_orchestra_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.MusicalSchool'),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_orchestra_source_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='instrumentsectionperformance',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Section'),
        ),
        migrations.AddField(
            model_name='instrumentperformance',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Recording'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.FormType'),
        ),
        migrations.AddField(
            model_name='form',
            name='images',
            field=models.ManyToManyField(related_name='andalusian_form_image_set', to='data.Image'),
        ),
        migrations.AddField(
            model_name='form',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='andalusian_form_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='form',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_form_source_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='albumrecording',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andalusian.Recording'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.AlbumType'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='andalusian.Orchestra'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description'),
        ),
        migrations.AddField(
            model_name='album',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='andalusian.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(related_name='andalusian_album_image_set', to='data.Image'),
        ),
        migrations.AddField(
            model_name='album',
            name='recordings',
            field=models.ManyToManyField(through='andalusian.AlbumRecording', to='andalusian.Recording'),
        ),
        migrations.AddField(
            model_name='album',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='andalusian_album_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='album',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='andalusian_album_source_set', to='data.Source'),
        ),
    ]
