# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andalusian', '0004_auto_20150826_1246'),
    ]

    operations = [
        migrations.RunSQL('alter table andalusian_album alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='album',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table andalusian_artist alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table andalusian_orchestra alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='orchestra',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table andalusian_recording alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='recording',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table andalusian_work alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='work',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
