# Generated by Django 2.1.7 on 2019-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andalusian', '0004_auto_20190122_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='original_name',
        ),
        migrations.AddField(
            model_name='instrument',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
