# Generated by Django 2.2.1 on 2019-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andalusian', '0005_auto_20190717_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nawba',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nawba',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tab',
            name='transliterated_name',
            field=models.TextField(),
        ),
    ]
