# Generated by Django 2.2.1 on 2019-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andalusian', '0005_auto_20190717_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='orchestra',
            name='school',
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mizan',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nawba',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nawba',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tab',
            name='transliterated_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='AlbumType',
        ),
        migrations.DeleteModel(
            name='FormType',
        ),
        migrations.DeleteModel(
            name='MusicalSchool',
        ),
    ]
