// filtersData
export const GET_FILTERS_DATA_REQUEST = 'GET_FILTERS_DATA_REQUEST';
export const GET_FILTERS_DATA_SUCCESS = 'GET_FILTERS_DATA_SUCCESS';
export const GET_FILTERS_DATA_FAILURE = 'GET_FILTERS_DATA_FAILURE';
export const TOGGLE_SELECTED_ENTRY = 'TOGGLE_SELECTED_ENTRY';
export const TOGGLE_EXPAND_CATEGORY = 'TOGGLE_EXPAND_CATEGORY';
export const RESET_CATEGORY_SELECTIONS = 'RESET_CATEGORY_SELECTIONS';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const RESET_SEARCH_CATEGORY = 'RESET_SEARCH_CATEGORY';

// search
export const AUTOCOMPLETE_REQUEST = 'AUTOCOMPLETE_REQUEST';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_FAILURE = 'AUTOCOMPLETE_FAILURE';
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';
export const TOGGLE_FOCUS = 'TOGGLE_FOCUS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_APPEND = 'SEARCH_APPEND';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';

// mobile menu
export const TOGGLE_FILTERS_MENU = 'TOGGLE_FILTERS_MENU';

// windowSize
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
