# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdiscovery', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('alter table motifdiscovery_file alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='file',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
