# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 15:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=200)),
                ('data', models.TextField(blank=True)),
                ('root_directory', models.CharField(max_length=200)),
            ],
            options={
                'permissions': (('read_restricted', 'Can read files in restricted collections'),),
            },
        ),
        migrations.CreateModel(
            name='CollectionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[(b'S', b'Staff-only'), (b'R', b'Restricted'), (b'U', b'Unrestricted')], default=b'S', max_length=1)),
                ('streamable', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docserver.Collection')),
            ],
            options={
                'permissions': (('access_restricted_file', 'Can see restricted source files'),),
            },
        ),
        migrations.CreateModel(
            name='DerivedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputname', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('mimetype', models.CharField(max_length=100)),
                ('computation_time', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DerivedFilePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_order', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('derivedfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='docserver.DerivedFile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('external_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('collections', models.ManyToManyField(related_name='documents', to='docserver.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='docserver.Document')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='EssentiaVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('sha1', models.CharField(max_length=200)),
                ('commit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('depends', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(max_length=200)),
                ('disabled', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('many_files', models.BooleanField(default=False)),
                ('collections', models.ManyToManyField(to='docserver.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docserver.Module')),
            ],
        ),
        migrations.CreateModel(
            name='PyCompmusicVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=200)),
                ('commit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcefiles', to='docserver.Document')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator(message=b'Slug can only contain a-z 0-9 and -', regex=b'^[a-z0-9-]+$')])),
                ('extension', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('mimetype', models.CharField(max_length=100)),
                ('stype', models.CharField(choices=[(b'audio', b'Audio'), (b'data', b'Data')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[(b'0', b'New'), (b'1', b'Updating'), (b'2', b'Updated')], default=b'0', max_length=1)),
                ('essentia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.EssentiaVersion')),
                ('pycompmusic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.PyCompmusicVersion')),
            ],
        ),
        migrations.AddField(
            model_name='sourcefile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docserver.SourceFileType'),
        ),
        migrations.AddField(
            model_name='module',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docserver.SourceFileType'),
        ),
        migrations.AddField(
            model_name='documentlogmessage',
            name='moduleversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.ModuleVersion'),
        ),
        migrations.AddField(
            model_name='documentlogmessage',
            name='sourcefile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.SourceFile'),
        ),
        migrations.AddField(
            model_name='derivedfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivedfiles', to='docserver.Document'),
        ),
        migrations.AddField(
            model_name='derivedfile',
            name='essentia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.EssentiaVersion'),
        ),
        migrations.AddField(
            model_name='derivedfile',
            name='module_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docserver.ModuleVersion'),
        ),
        migrations.AddField(
            model_name='derivedfile',
            name='pycompmusic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docserver.PyCompmusicVersion'),
        ),
        migrations.AddField(
            model_name='collectionpermission',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docserver.SourceFileType'),
        ),
    ]
