# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedfile',
            name='num_parts',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL("update docserver_derivedfile set num_parts = (select count(*) from docserver_derivedfilepart where derivedfile_id = docserver_derivedfile.id)"),
        migrations.AlterField(
            model_name='derivedfile',
            name='num_parts',
            field=models.IntegerField(),
        ),
    ]
