# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docserver', '0002_derivedfile_num_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivedfilepart',
            name='derivedfile',
        ),
        migrations.DeleteModel(
            name='DerivedFilePart',
        ),
    ]
