# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docserver', '0003_auto_20161212_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='derivedfile',
            unique_together=set([('document', 'module_version', 'outputname')]),
        ),
    ]
