# Generated by Django 2.1.2 on 2019-01-22 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docserver', '0004_auto_20161212_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpermission',
            name='permission',
            field=models.CharField(choices=[('S', 'Staff-only'), ('R', 'Restricted'), ('U', 'Unrestricted')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='sourcefiletype',
            name='slug',
            field=models.SlugField(validators=[django.core.validators.RegexValidator(message='Slug can only contain a-z 0-9 and -', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='sourcefiletype',
            name='stype',
            field=models.CharField(choices=[('audio', 'Audio'), ('data', 'Data')], max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.CharField(choices=[('0', 'New'), ('1', 'Updating'), ('2', 'Updated')], default='0', max_length=1),
        ),
    ]
