# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docserver', '0012_collection_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collectionid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table docserver_collection alter COLUMN collectionid type uuid USING ("collectionid"::uuid)'),
        migrations.AlterField(
            model_name='collection',
            name='collectionid',
            field=models.UUIDField(),
        ),
    ]
