# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_images(apps, schema_editor):
    Artist = apps.get_model("carnatic", "Artist")
    Composer = apps.get_model("carnatic", "Composer")
    Concert = apps.get_model("carnatic", "Concert")
    Instrument = apps.get_model("carnatic", "Instrument")
    Raaga = apps.get_model("carnatic", "Raaga")
    Taala = apps.get_model("carnatic", "Taala")
    migrate_images_for_class(Artist)
    migrate_images_for_class(Composer)
    migrate_images_for_class(Concert)
    migrate_images_for_class(Raaga)
    migrate_images_for_class(Taala)

    for item in Instrument.fuzzymanager.all():
        if item.images.count():
            i = item.images.all()[0]
            item.image = i
            item.save()


def migrate_images_for_class(Klass):
    for item in Klass.objects.all():
        if item.images.count():
            i = item.images.all()[0]
            item.image = i
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('carnatic', '0002_auto_20161005_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='raaga',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taala',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_artist_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='composer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_composer_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_concert_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_instrument_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='raaga',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_raaga_image', to='data.Image'),
        ),
        migrations.AddField(
            model_name='taala',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnatic_taala_image', to='data.Image'),
        ),
        migrations.RunPython(migrate_images),
    ]
