# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic', '0003_auto_20161005_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='images',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='images',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='images',
        ),
        migrations.RemoveField(
            model_name='raaga',
            name='images',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='images',
        ),
        migrations.RemoveField(
            model_name='taala',
            name='images',
        ),
        migrations.RemoveField(
            model_name='work',
            name='images',
        ),
    ]
