# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic', '0015_instrumentperformance_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raaga',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table carnatic_raaga alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='raaga',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taala',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table carnatic_taala alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='taala',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
