# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic', '0016_auto_20160909_1109'),
    ]

    operations = [
        migrations.RunSQL('alter table carnatic_artist alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table carnatic_composer alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='composer',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table carnatic_concert alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='concert',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table carnatic_instrument alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='instrument',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table carnatic_recording alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='recording',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunSQL('alter table carnatic_work alter COLUMN mbid type uuid USING ("mbid"::uuid)'),
        migrations.AlterField(
            model_name='work',
            name='mbid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
