# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 15:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carnatic', '0017_auto_20160912_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagealias',
            name='language',
        ),
        migrations.DeleteModel(
            name='MusicalSchool',
        ),
        migrations.AlterModelManagers(
            name='instrument',
            managers=[
                ('fuzzymanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='instrumentalias',
            managers=[
                ('fuzzymanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='raagaalias',
            managers=[
                ('fuzzymanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taalaalias',
            managers=[
                ('fuzzymanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='sabbah',
        ),
        migrations.RemoveField(
            model_name='work',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='LanguageAlias',
        ),
        migrations.DeleteModel(
            name='Sabbah',
        ),
    ]
