# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import makam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('artist_type', models.CharField(choices=[(b'P', b'Person'), (b'G', b'Group')], default=b'P', max_length=1)),
                ('dummy', models.BooleanField(db_index=True, default=False)),
                ('description_edited', models.BooleanField(default=False)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('group_members', models.ManyToManyField(blank=True, related_name='groups', to='makam.Artist')),
                ('images', models.ManyToManyField(related_name='makam_artist_image_set', to='data.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='ArtistAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('primary', models.BooleanField(default=False)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='makam.Artist')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True)),
                ('begin', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='makam_composer_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='makam_composer_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_composer_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='ComposerAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('primary', models.BooleanField(default=False)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='makam.Composer')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='makam.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percussion', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('name_tr', models.CharField(max_length=50)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='makam_instrument_image_set', to='data.Image')),
                ('references', models.ManyToManyField(blank=True, related_name='makam_instrument_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_instrument_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='InstrumentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.BooleanField(default=False)),
                ('attributes', models.CharField(blank=True, max_length=200, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Artist')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makam.Instrument')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='Makam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tonic_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('mu2_name', models.CharField(blank=True, max_length=250, null=True)),
                ('symtr_key', models.CharField(blank=True, max_length=250, null=True)),
                ('uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakamAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('makam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='makam.Makam')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('has_taksim', models.BooleanField(default=False)),
                ('has_gazel', models.BooleanField(default=False)),
                ('analyse', models.BooleanField(default=True)),
                ('artists', models.ManyToManyField(related_name='recordings_artist', to='makam.Artist')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='makam_recording_image_set', to='data.Image')),
                ('makam', models.ManyToManyField(blank=True, to='makam.Makam')),
                ('performance', models.ManyToManyField(through='makam.InstrumentPerformance', to='makam.Artist')),
                ('references', models.ManyToManyField(blank=True, related_name='makam_recording_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_recording_source_set', to='data.Source')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='RecordingWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Recording')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('artistcredit', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_concert', models.BooleanField(default=False)),
                ('artists', models.ManyToManyField(related_name='primary_concerts', to='makam.Artist')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_releases', to='data.Collection')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('images', models.ManyToManyField(related_name='makam_release_image_set', to='data.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.CreateModel(
            name='ReleaseRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Recording')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Release')),
            ],
            options={
                'ordering': ('track',),
            },
        ),
        migrations.CreateModel(
            name='SymbTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsulAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='makam.Usul')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mbid', models.UUIDField(blank=True, null=True)),
                ('composition_date', models.CharField(blank=True, max_length=100, null=True)),
                ('composers', models.ManyToManyField(blank=True, related_name='works', to='makam.Composer')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Description')),
                ('form', models.ManyToManyField(blank=True, to='makam.Form')),
                ('images', models.ManyToManyField(related_name='makam_work_image_set', to='data.Image')),
                ('lyricists', models.ManyToManyField(blank=True, related_name='lyric_works', to='makam.Composer')),
                ('makam', models.ManyToManyField(blank=True, to='makam.Makam')),
                ('references', models.ManyToManyField(blank=True, related_name='makam_work_reference_set', to='data.Source')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_work_source_set', to='data.Source')),
                ('usul', models.ManyToManyField(blank=True, to='makam.Usul')),
            ],
            options={
                'abstract': False,
            },
            bases=(makam.models.MakamStyle, models.Model),
        ),
        migrations.AddField(
            model_name='release',
            name='recordings',
            field=models.ManyToManyField(through='makam.ReleaseRecording', to='makam.Recording'),
        ),
        migrations.AddField(
            model_name='release',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='makam_release_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='release',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_release_source_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='recordingwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Work'),
        ),
        migrations.AddField(
            model_name='recording',
            name='works',
            field=models.ManyToManyField(through='makam.RecordingWork', to='makam.Work'),
        ),
        migrations.AddField(
            model_name='instrumentperformance',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makam.Recording'),
        ),
        migrations.AddField(
            model_name='artist',
            name='main_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makam.Instrument'),
        ),
        migrations.AddField(
            model_name='artist',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='makam_artist_reference_set', to='data.Source'),
        ),
        migrations.AddField(
            model_name='artist',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='makam_artist_source_set', to='data.Source'),
        ),
    ]
