# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makam', '0003_auto_20161006_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='has_lyrics',
            field=models.BooleanField(default=False),
        ),
    ]
