# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makam', '0010_work_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='is_processed',
        ),
    ]
