# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('makam', '0011_remove_work_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table makam_form alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='form',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='makam',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table makam_makam alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='makam',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usul',
            name='uuid',
            field=django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True),
        ),
        migrations.RunSQL('alter table makam_usul alter COLUMN uuid type uuid USING ("uuid"::uuid)'),
        migrations.AlterField(
            model_name='usul',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
